# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9223354f46ae8339a90b522d2bdb789431dbf8dc4ed8ae9715e68d8e39ac23cfec602e445ca95194b35918de7bff1750d55220d8b51c2a3e44d6251802de4cd

test:
  secret_key_base: 21be8b45dcc382f51a2ef0234558ec4cdd2f4d1f4e970bec32d63e3b21bb448a018920245ebb5de33efc924f776be4298f55b922bf1977e2a8e02c4088519c45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
