# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7aa1fcae20a4511b7e8948f7013ae6edd3d95a1c6a58b89adbd84f31fc83b4a427a11ed155c1f424bbc52148d822e9deff6e9df2ccd473b57862ae9bc3384529

test:
  secret_key_base: 7a501948d78aee014a2d7eab44e6242b3c0f3babaf75b5ea64f2b817bf5c6edae4c61103f699b70467a218bb6b0381aada2c6233e446645671dc27aaa8cea4af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
